import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {SessionProvider} from "next-auth/react";
import { Providers } from "@/components/provider/providers";
import { auth } from "@/auth";
import {Toaster} from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session=await auth();
  return (
    <SessionProvider>   
     <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster/>
          {children}
        </Providers>
        </body>
    </html>
    </SessionProvider>
 
  );
}
